[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="reports/accueil.html"
    path = "" #la racine du site

[[plugins.inputs.audits]]
    output_path="reports/contact.html"
    path = "/fr/contact.html" #la racine du site
