[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="reports/accueil.html"
    path = "" #la racine du site

    [[plugins.inputs.audits]]
    output_path="reports/contact.html"
    path = "/fr/contact.html" #la racine du site

    [[plugins.inputs.audits]]
    output_path="reports/a_propos.html"
    path = "/fr/a_propos.html" #la racine du site

    [[plugins.inputs.audits]]
    output_path="reports/billeterie.html"
    path = "/fr/billeterie.html" #la racine du site

    [[plugins.inputs.audits]]
    output_path="reports/serguei_paradjanov.html"
    path = "/fr/serguei_paradjanov.html" #la racine du site

    [[plugins.inputs.audits]]
    output_path="reports/serguei_oeuvre_radko.html"
    path = "/fr/serguei_oeuvre_radko.html" #la racine du site
